version: "3.9"
services:
  calculator:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./CalculatorApp:/app
    environment:
      - NODE_ENV=production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3